import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.locator("body").click()
    page.goto("https://www.saucedemo.com/")
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("Problembenutzer")
    page.get_by_text("geheime Soße").click()
    page.locator("[data-test=\"login-password\"]").click()
    page.locator(".error-message-container").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("geheime Soße")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("geheime Soße")
    page.locator("[data-test=\"password\"]").press("Enter")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("svg").nth(4).click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("path").nth(4).click()
    page.locator("[data-test=\"username\"]").fill("Standardbenutzer")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"password\"]").click()
    page.locator("[data-test=\"password\"]").fill("geheime Soße")
    page.locator("[data-test=\"password\"]").press("Enter")
    page.locator("[data-test=\"password\"]").press("Enter")
    page.locator("[data-test=\"password\"]").press("Enter")
    page.locator("[data-test=\"password\"]").press("Enter")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("visueller Benutzer")
    page.locator("[data-test=\"login-button\"]").click()
    page.goto("https://www.saucedemo.com/")
    page.locator("[data-test=\"login-credentials\"]").click()
    expect(page.locator("[data-test=\"username\"]")).to_be_visible()
    expect(page.locator("[data-test=\"username\"]")).to_be_empty();
    expect(page.locator("[data-test=\"login-button\"]")).to_match_aria_snapshot("- button \"Login\"")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standard")
    page.locator("[data-test=\"username\"]").press("ControlOrMeta+Shift+_")
    page.locator("[data-test=\"username\"]").fill("standardus")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").fill("standard_us")
    page.locator("[data-test=\"username\"]").press("ArrowRight")
    page.locator("[data-test=\"username\"]").press("ArrowRight")
    page.locator("[data-test=\"username\"]").fill("standard_user")
    page.locator("[data-test=\"username\"]").press("Tab")
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    page.get_by_role("button", name="Open Menu").click()
    page.locator("[data-test=\"logout-sidebar-link\"]").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
